### ISSUE TITLE
/apply in game gives you old apps that don't go through

### ISSUE THREAD

**Issue by piplupqueenn** [SmashMC-Development/Bugs-and-Issues#1075]
**Describe the Bug**
Do /apply in game
**To Reproduce**
See that it is not the same application in the SmashMC discord. 

**Servers with the Bug**
Please provide a list of which servers have this bug.
All
**Expected behavior**
Expected to be the accurate application which is in the SmashMC discord. 
**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by HackuJacku** [comment]
Both links take you to the same website so what exactly is the issue please, @piplupqueenn?

**Comment by jantjewieger** [comment]
Think the issue was that the one form /apply sends you to an old document. When u open that one its still the one dan made. Whereas the one in the discord is the new one from super. Its a different link to a different form. Don't know if this is the issue but might be that the old one from dan doesn't get read by super or he has no access to it idk

![image](https://user-images.githubusercontent.com/87021826/150864397-73b27407-e97e-4e7f-a394-69cbab2ea6ab.png)

![image](https://user-images.githubusercontent.com/87021826/150864450-ccf58492-162b-4c46-8046-715f49c8eabb.png)

**Comment by piplupqueenn** [comment]
yes that's what I mean, sorry for not explaining more

**Comment by Superfire96** [comment]
Fixed
