### ISSUE TITLE
perms and claimflag stuff

### ISSUE THREAD

**Issue by manlybro2002** [SmashMC-Development/Bugs-and-Issues#1111]
**Describe the Bug**
perms mess with Public claimflag stuff since perms take a higher priority. e.g. 
occupied-pokeball-usage false which is meant to stop ppl sendin out mons in the claim doesnt work if they have any kind of perms.

other Public claimflag stuff that perms mess with:
chest access (minimum container)
sleep (minimum accessor)
interact-with-endtable (minimum container)
interact-with-fridge (minimum container)
interact-with-healer (minimum container)
throw any pokeball  (minimum accessor)
use-cushion-chairs (minimum accessor)
use-fossil-cleaner (minimum accessor)
use-fossil-machines (minimum accessor)
use-pc (minimum accessor)
use-trade-machines (minimum accessor)
use-vending-machines (minimum accessor

**Expected behavior**
why suggest this? It is because Owner claimflag stuff work so it only makes sense for the Public claimflag to work over perms.

**Which servers does this apply to?**
all pixelmon servers

**additional context**
definitely didnt forget i disabled my own chest access and almost made a ticket doing this...but to be honest having public claimflag take higher priority over perms would make claims with uhh some complexity easier to make, e.g. chest access is disabled but players can still use other blocks that need container perms.

**Comment by Mikirae** [comment]
Hi Ras another GriefDefender ticket just for you <3

**Comment by Rasgnarok** [comment]
"occupied-pokeball-usage false which is meant to stop ppl sendin out mons in the claim doesnt work if they have any kind of perms"
What kind of perms? If you give them /trust levels, it's meant to override it. That's how the plugin works.

**Comment by Rasgnarok** [comment]
" Public claimflag to work over perms"
That's on purpose. There's global flags so that it overrides every other type of perm, globally. I don't want private claims to prevent PC usage, for instance. These minimum accessors? They are meant to work atop your owner-set flags.

Please give me an example of what you mean, because honestly, ticket's a bit convoluted.

**Comment by manlybro2002** [comment]
I just wanted public claimflag to work the same way owner claimflag does, as in having higher priority over perms.

The way I understood the perms is owner>manager>builder>container>accessor>untrusted. So I tested owner claimflags and figured that Claimflag>owner>etc. but after finding out that its actually 
Owner Claimflag>Owner>manager>builder>container>accessor>Public Claimflags>untrusted 
I thought that was wrong and mentioned this as a bug.

 As an example of what currently happens; I can disable my own access to chests in my own claim but if I disable it for other players that have container perms, they are still able to use chests. 

What I'm expecting to happen is that players with container perms to not be able to access the chests when I disable it through public claimflag. 

I'm using this example since I was expecting to be able to create public areas for blocks that need container perms - e.g. enchanting table, furnaces etc. - without letting players with container perms touch chests.

Other claimflags were mentioned because I was wondering if it could be applied generally but now I guess I should look for specific changes.

If that's how the plugin works then I guess it cant be helped. I'll just find a different ways to make public areas.

**Comment by Rasgnarok** [comment]
Public areas already inherently work, because there should be an active overwrite for machines, enchant tables, crafting table, etc. When I talk of 'public' flags, I mean global flags - these are forced to true for specific interacts, like NPCs, throw-pokeball, pc-use, etc.

Yes, your hypothesis is correct, GD prioritizes trust levels over flags, they are separate systems. To be fair, to be touching your own flags is a dangerous ball game.
