### ISSUE TITLE
Safeplace

### ISSUE THREAD

**Issue by oLimooo** [SmashMC-Development/Bugs-and-Issues#112]
**Describe the Bug**
Players  are able to /safeplace whilst in warzone battle

**To Reproduce**
1. Go to warzone
2. get into a battle
3. /safeplace

**Servers with the Bug**
all

**Expected behavior**
players are not supposed to be able to /safeplace while in a warzone battle.

**Screenshots**
N/a'.

**Additional context**
N/a'.

**Comment by luke04683** [comment]
Suggestion 

I would like to suggest that a chat blocker of some sort could be added. 

This can include things to stop spam and character dragging this way for people like me who accidentally character drag will not be able to send the message if it has over 4 of the same letters together.

I want to suggest this because I have been muted for 15 minutes for character dragging but I’m not even realizing I’m doing it so this is kind of unfair to people like me.

**Comment by HackuJacku** [comment]
@luke04683 - please create a separate, new suggestion.

**Comment by luke04683** [comment]
> @luke04683 - please create a separate, new suggestion.

I don’t know how to do this

**Comment by HackuJacku** [comment]
> > @luke04683 - please create a separate, new suggestion.
> 
> I don’t know how to do this

Follow this guide: https://pokesmash.enjin.com/forum/m/51608256/viewthread/33527612-creating-bugissue-or-suggestion-on-smashmc-github

**Comment by HackuJacku** [comment]
Fixed in Warzone 2.0.
