### ISSUE TITLE
Pokemon Plushies to place on claims.

### ISSUE THREAD

**Issue by Artroy7** [SmashMC-Development/Bugs-and-Issues#1259]
The Idea is to get small still standing Pokemon Statues.

The Satues can be obatained from Crates or the Server Shop itself.

The Staues/Plushies should work as sum Decor Block so you can place them on a Claim.

Perhaps limit the Placement of the Statues to not overflow a claim with them.

The Plushies could also be sold in GTS as Decor Items.

**Comment by BigChungv2** [comment]
Like a new collectible, rarer ones for special events and maybe even shiny versions of legendaries that can only be obtained through something like elite 4 wins or when someone hits a certain dex percentage

**Comment by Archie4690** [comment]
@Artroy7 Funny you say this. The ability to have Pokemon statues is now added in the new event's crate that is out as of today. Keep an eye out and see if you can get yourself one this weekend! Also, next time this would be better suited to our suggestions panel! With that being said I will close this up since it is already added!
