### ISSUE TITLE
Reset coming up

### ISSUE THREAD

**Issue by DarrenC07** [SmashMC-Development/Bugs-and-Issues#1270]
Just wondering why this upcoming reset forbids us from banking pokemon. Based on my knowledge, all previous resets allowed at least 1 banked pokemon so I was confused as to why this reset we can't. This is especially since new exclusive special texture pokemon were literally released not too long ago (i,e, easter and valentine's). I understand having crates being refunded but when it comes to these limited crates or even papers like specific legendaries or shadow textured pokemon, banking them is really the only way to keep those textures since they aren't refunded at all. If someone could help me clarify that would be amazing.

**Comment by DarrenC07** [comment]
Oh yeah, it's also not like we could trade/breed/sell the banked pokemons anyways because they come as untradeable and unbreedable. It also makes it so we can't bring into warzone so it's stuck with us until end of that reset.

**Comment by RatedPG21** [comment]
As the server is going from 1.12 to 1.16.5, the data packs can’t transfer over so there isn’t a way for the Pokémon to be transferred over different versions. Also the management team had thought it better for everyone to start on a clean slate.

**Comment by DarrenC07** [comment]
If it's a data pack issue, I completely understand. However, is there no compensation for other store bought items? For example, a random shadow leg paper costs more than a single crate key and even a random shadow pokemon paper costs the same as a cosmetic crate key. Do these not deserve to be refunded as well?

**Comment by RatedPG21** [comment]
As said in the announcement, all store purchases within the last 3 months are automatically refunded

**Comment by morrow12** [comment]
"Start on a clean slate" so ppl who spent 5k+ on crates they get a huge headstart which is so bs

**Comment by RatedPG21** [comment]
There isn’t a way to satisfy everyone here. If we don’t give refunds to those who spent money, then they will feel scammed and obviously we don’t want that. On the other hand if we do, people will complain. I believe this is the best we can do

**Comment by BrunchBee** [comment]
> "Start on a clean slate" so ppl who spent 5k+ on crates they get a huge headstart which is so bs

The people who can afford to spend that much money on the server usually just purchase new crates after a reset anyways. They would have a "head start" regardless. Not that a head start or clean slate really matter. The only thing there's a head start to do is get battle perfect pokemon if you go to warzone. However, it'd be weird to revolve every decision solely around warzone. 

It would also defeat the purpose of purchasing crate keys in the first place. If you bought mystic crates to get IV boosts and nature changes, it would most likely to be to speed up the breeding process. AKA get a head start compared to those who do not have IV boosts. So it wouldn't make much sense to say "oh you are getting a head start because you donated, that isn't fair". That is pretty much half the point of buying crates

**Comment by DarrenC07** [comment]
I understand refunding purchases but how was the decision to only refund the last 3 months made? What I’m saying is how is that “fair” for donators that bought from the store before march? I can come up with plenty of donators who have spent quite a bit before March but not so much after. This causes them to not be able have any of their stuff yet they aren’t qualified for a refund so still “scammed” in a sense.

Also, I read somewhere on discord where apparently pixelmon data is actually transferable. Will this new information be taken into account for the upcoming reset?

**Comment by Chungers01** [comment]
As a player on smashmc since early March of 2020, I have to say staff's decision to completely reset is irresponsible and insincere.  This server grew big recently not ONLY because of Sirud's Youtube, but because of the community that we have.  Players used their money to benefit themselves in their gaming experiences, but also to donate more to the server so that higher ends of the staff can improve the server to make the game enjoyable for everyone.  

Most people who played on this server since the beginning of the reset are gone because of lack of entertainment on the server.  Those people paid hundreds to get the pokemons that they have and kept one pokemon to bring to the reset after enjoying the server.  Based on new announcement, would they receive any compensation for helping server grow more? No, they won't according to any staff members responding to players.  

Why would those people comeback? Even people who play until the last day before the reset say they might just quit since everything that they worked for is going to waste.  Even I think that I wasted my time/money on this server even though I've always loved playing on this server.  

Also, based on my experience, people who gets to bring one pokemon to reset does not gain any advantage over anyone who starts from scratch.  It can't be bred, traded, or taken to warzone and this means it is a souvenir of your past memories on this server.  If you look through the discord as staff, you will find one of you staff members telling me specifically that players get to take one pokemon as a souvenir.  I know a staff member said this when I was disappointed that I couldn't take 3 pokemons when lucario reset to rayquaza.  Their response was fair and understandable.

This one? Definitely not fair.  Why would anyone who spent hundreds earlier days of the server spend more money if they know they can't be compensated in any way?  These players are what helped this server grow.  I completely agree with money compensation for any purchases from last 3 months as those people didn't really get to enjoy what they paid for.  But are you just going to ignore those people who played on the server since the beginning of the reset?  

If I spent as much as some people (I know several people who spent more than $500 in the first week of reset), I would be very mad and request a full refund.  But of course, server can't do that.  This is why server needs to compensate those people by "AT LEAST" allowing players to take one pokemon as a souvenir.  

I also need to say, don't make us, the players, think that staff just didn't want to make pokebank and rushed the reset with the upcoming update.  Because it has only been about 7 or 8 months while previous reset lasted about 10 to 11 months. I obviously respect the staff for always putting in the hard work to keep the server running, but as an experienced player of the server, I would like to see different options than ignoring the contributions of people who played earlier days of the server.

**Comment by Chungers01** [comment]
> On the other hand if we do, people will complain. I believe this is the best we can do

By the way, I am very sure that no one will complain if everyone received a refund and not be able to take anything to reset.  However, if they can't bring anything to the reset, I am also very sure that people will be very mad as there are very many people who don't receive any compensation.

I have no intention to start an argument with staff.  I am just trying to help make it more fair to everyone.

**Comment by BGG100** [comment]
Definitely don't see the justification of removing pokebank. I'm sure some players have pokebanked mons spanning back to Lucario times, to randomly remove it now seems both unjustified and senseless. 

If the pokemon are untradeable/unbreedable, what is the advantage given, besides a simple display/token pokemon? If the reason for removing pokebank is to avoid players having a BP legend for warzone off start, can it simply not be implemented that these banked pokemon cannot be brought to warzone? 

I speak for the majority when I say many individuals are bringing over textured pokemon that they purchased during a holiday event. Removing pokebank not only makes these textured mons completely extinct network wide, but it also deincentivizes individuals from purchasing textured mons in the future. From a business/marketing standpoint, the removal of pokebank still makes little sense.

If I'm missing a bigger picture here, please feel free to explain. I genuinely do not understand the justification behind removing pokebank.

**Comment by Archie4690** [comment]
Purging all old GitHubs, Thank you for your contributions!
