### ISSUE TITLE
Raids spawn rate is messed up on reshiram

### ISSUE THREAD

**Issue by O-G-Banana1** [SmashMC-Development/Bugs-and-Issues#1365]
**Describe the Bug**
There are little to no raids spawning on reshiram i have checked over 130 dens and haven't found one active raid. This just happened in the recent 9.0.4 update before that there was a steady flow of active raid dens to be found but now i cannot seem to find any. This is not only my opinion the majority of the server community shares the same concern. The reason this is important is because it's the main way to make money in this economy and if we can't find raids, we can't earn money. 

**To Reproduce**
Go look for active raid dens on reshiram 

**Servers with the Bug**
Please provide a list of which servers have this bug.
Reshiram, havent checked others 
**Expected behavior**
I would like the staff to check the raid spawn rate on Reshiram. Change it back to what it was before the update idk what changed but it messed it up. 

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
Username: O-G-Banana1 Server: Reshiram

**Comment by Johann12345555** [comment]
This is the exact same on kyogre. When 2 other players align with me checked 90 different dens or so total only 1 was active.

**Comment by Jeroenvan8** [comment]
Haven't seen them as fast as normally either on Zekrom

**Comment by Mikirae** [comment]
Sorry, been busy these past few days. You're saying that this issue began when we updated to 9.0.4? And before this, they were spawning perfectly fine?

**Comment by O-G-Banana1** [comment]
Yes before the updates the rates were very well balanced Now you can
probably only find 1 active raid a day if your looking really hard. Idk
what the rates are but they seem to be on all servers extremely low

**Comment by Mikirae** [comment]
I did something last night after seeing these tickets to hopefully make them become active more frequently. Please let me know if it works!
If not, it might be a bug with Pixelmon :(

**Comment by O-G-Banana1** [comment]
I have checked over 200 dens today and have only found 1 raid. Whatever you tried, did not help still extremely low spawn rate

**Comment by DinglePringleUwU** [comment]
Kyogre Player here. We have the same issue.

I have made some test runs today. 
I tested 100 Raid dens. (25 In Overworld, 25 in Ultra, 25 in Nether and 25 in The End) five times over a course of five minecraft days. Smash rank helps greatly with doing that due to unlimited homes.
I started these runs at exactly 100ticks (Time at which the raid dens recharge)
Out of these 100 i had four working raid dens on every try. And surprisingly enough, most of the time, they were even the exact same raid dens. The one i stood next to while waiting for the recharge always worked.
One thing these raid dens had in common was, that there was something a player build near them. Plats for example.
The Raid dens that worked were either in ultra or overworld dimension. 

I made two runs to be precise. The first five tries right after serverstart when pokespawns were plentyful, and the second five tries roughly 8 Hours later after the pokespawns were struggling. There was no difference tho.

A guess: Maybe they only activate if a player is/was nearby when the activation triggers.

**Comment by O-G-Banana1** [comment]
I’ve been playing all day and the rates seem to be the same. The rates are
still very low have yet to find a single raid yet

**Comment by DinglePringleUwU** [comment]
Imo the rates of active raids has improved drastically and are currently pretty solid.
The issue that was existing in 9.0.4 is gone.

**Comment by Paradis4432** [comment]
inactive
