### ISSUE TITLE
Poke Spawns 

### ISSUE THREAD

**Issue by Kakarott9000** [SmashMC-Development/Bugs-and-Issues#1420]
**Describe the Bug**
This bug consist of Pokémon rarely spawning and also bosses.. -AlphaPred2x
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jantjewieger** [comment]
The pokemon rarely spawning is, unfortunately, a pixelmon issue and not something we can control. The bosses have a very low spawn rate because they are supposed to be quite rare. If you feel like they should be made more common you can, of course, make a suggestion github about that. I do want to ask you to follow the proper format when creating a github because this github doesn't really help us when dealing with bugs :p . That being said I will be closing this up
