### ISSUE TITLE
Cant Catch Reshi from lucky Block

### ISSUE THREAD

**Issue by Husklol** [SmashMC-Development/Bugs-and-Issues#1421]
When opening a lucky I was unable to catch the reshiram that had been spawned out of it

**Comment by jantjewieger** [comment]
I tested this and it worked fine for me. Only the person that opens the lucky block can catch it. Your friend opened the lucky block (as i saw when I checked the logs u sent in the ticket) and that means that you cannot catch the pokemon that comes out of it, only him. Closing this up as that is where the problem lies
