### ISSUE TITLE
Ampharous Breeding Block Bug?

### ISSUE THREAD

**Issue by Kakarott9000** [SmashMC-Development/Bugs-and-Issues#1427]
**Describe the Bug**
The bug or what I believe could be a bug is when breeding electric types (Ampharous)....I'm not sure if its only Ampharous.......... But I'm using lit Redstone lamps which are supposed to be considered a value of 3 but when I click on them instead of saying the 3 value line it says they're "more attracted" I'm not sure though but please correct me if wrong... Thanks <3 
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by jantjewieger** [comment]
Pretty sure, but someone, who is a breeding god, can correct me on this if im wrong, that its not just about the block they are breeding with but that it's also the attraction 2 mons have towards each other. Pretty sure that that is the issue here. That its just these 2 mons that arent fully 100% attracted to each other. I do wanna add to this that, if this is actually an issue, it would be a pixelmon issue and not something we, that being SmashMC, can fix

**Comment by Kakarott9000** [comment]
> Pretty sure, but someone, who is a breeding god, can correct me on this if im wrong, that its not just about the block they are breeding with but that it's also the attraction 2 mons have towards each other. Pretty sure that that is the issue here. That its just these 2 mons that arent fully 100% attracted to each other. I do wanna add to this that, if this is actually an issue, it would be a pixelmon issue and not something we, that being SmashMC, can fix
 
Thanks!! I thought I was losing my mind because I thought maybe it was because of ampharous and mareep. But now im breeding two mareep and its still doing the same thing but ill go mining to get redstone blocks to hopefully speed this up because now its taking forever

**Comment by Mikirae** [comment]
Closing this because I think it's fixed and breeding is different now
