### ISSUE TITLE
Some commands don't work for dex ranks. 

### ISSUE THREAD

**Issue by ChemMajorBTW** [SmashMC-Development/Bugs-and-Issues#1458]
**Describe the Bug**
Some commands do not work from dex ranks. Specifically all /vaults commands, /leveling, /anvil and /enchantingtable

**Servers with the Bug**
All I know is reshiram.

**Expected behavior**
For the commands to work.

**Comment by jantjewieger** [comment]
This is not because they don't work but because the description of dexrank needs to be updated. At least for /vaults that is definitely the case. I know that dexranks arent supposed to have access to /vaults or /bpk and that just the description needs to be updated as its just a feature for paid ranks. As for the other commands i'm not too sure but I'd assume thats the same story. But a manager might have to correct me on that

**Comment by Superfire96** [comment]
Fixed
