### ISSUE TITLE
Fusions and other bugs

### ISSUE THREAD

**Issue by ketl0rd** [SmashMC-Development/Bugs-and-Issues#1498]
Fusion mons signature moves need to be tested to ensure they work correctly. Atm I've tested the signature moves for Grouchomp and Aggrizard. 
Grouchomp's move states it can hit flying type mons however trying it, it does not work 
Aggrizard's move takes 50% of its health not 50% of the dmg dealt not sure which way it's meant to work but the move does no damage to its target and just burns it. 
I'm assuming that some of the other moves do not work correctly as well so would be good to get them fixed. 

/buymoves isnt currently working for most mons. I have been able to use it on very few but the majority of the time it does not work

**Comment by Mikirae** [comment]
Grouchomp's move is currently bugged. We realized it was bugged because of a miscommunication between me and the dev. Lol. That one is fixed tonight.
Aggrizard is supposed to work just like Mind Blown, you take 50% of your health every time you use the move.
The move 100% damages the target though. I've tested that and I saw Sirud use it on the live server and it did damage.

Buymoves is bugged and the dev is taking exams, so there's really not much we can do. I've been nagging, but he hasn't had time.
