### ISSUE TITLE
Treasures at spawn not showing claim already

### ISSUE THREAD

**Issue by GiratinaLord** [SmashMC-Development/Bugs-and-Issues#1859]
When I Rick Click on the Treasures it doesnt say anything in Minecraft Chat

**Comment by Paradis4432** [comment]
please provide all the requested information

Describe the Bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Servers with the Bug
Please provide a list of which servers have this bug.

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

Additional context
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
inactive
