### ISSUE TITLE
Claimed rewards but no reward

### ISSUE THREAD

**Issue by psychoticraichu9** [SmashMC-Development/Bugs-and-Issues#1861]
**Describe the Bug**
Claimed Dex rewards and it gave me everything but the fusion shard.

**Comment by psychoticraichu9** [comment]
Also never gave me my shiny triple choice

**Comment by psychoticraichu9** [comment]
anddddddd my leftovers disappeared as well...

**Comment by Paradis4432** [comment]
please provide all the requested information

Describe the Bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Servers with the Bug
Please provide a list of which servers have this bug.

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

Additional context
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by psychoticraichu9** [comment]
Claimed Dex rewards and it gave me everything but the fusion shard. again I am now missing 4-5 shards from it

**Comment by Paradis4432** [comment]
missing server screenshoots aditional context steps

**Comment by psychoticraichu9** [comment]
Describe the Bug
Fusion shards and triple shiny choice was not received after claiming dex rewards 50% and 25%

To Reproduce
Steps to reproduce the behavior:

no way to reproduce since I can no longer claim it

Expected behavior
I just want those rewards

Screenshots
Dont have a way to screen shot something that is missing

Additional context
n/a

**Comment by Paradis4432** [comment]
on what server was this ?

**Comment by psychoticraichu9** [comment]
Rayquaza On Sep 4, 2023, at 9:53 PM, Paradis ***@***.***> wrote:﻿
on what server was this ?

**Comment by Paradis4432** [comment]
should be fixed

**Comment by psychoticraichu9** [comment]
I didn’t get anything back?Sent from my iPhoneOn Sep 14, 2023, at 9:42 PM, Paradis ***@***.***> wrote:﻿
should be fixed

**Comment by Paradis4432** [comment]
there were no screnshoots, videos, logs provided, impossible to return anything with that information

**Comment by psychoticraichu9** [comment]
Again…. How can I screenshot something that isn’t there? I don’t screen record 24/7. I don’t have a log for it? So I just don’t get the rewards?On Sep 15, 2023, at 5:22 PM, Paradis ***@***.***> wrote:﻿
there were no screnshoots, videos, logs provided, impossible to return anything with that information

**Comment by Paradis4432** [comment]
please contact management for further assistance, i cant do anything else
