### ISSUE TITLE
i cant send out my pokemon

### ISSUE THREAD

**Issue by perolol** [SmashMC-Development/Bugs-and-Issues#1865]
i cant send out my pokemon even tho im spamming R to send out the pokemon

**Comment by Paradis4432** [comment]
please provide all the requested information

**Describe the Bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.
