### ISSUE TITLE
When I evelov a pokemon it shows me a first view angle and it doesn't evelov the pokemon for me it only shows the effects. my name is ItayNasi in mincraft

### ISSUE THREAD

**Issue by itay35432** [SmashMC-Development/Bugs-and-Issues#1875]
**Describe the Bug**

**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by Paradis4432** [comment]
you need to provide some more that for us to replicate the issue, thats why theres a template 

Describe the Bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Servers with the Bug
Please provide a list of which servers have this bug.

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

Additional context
Add any other context about the problem here. If nothing, please add 'N/A'.
