### ISSUE TITLE
cant send out my pokemon

### ISSUE THREAD

**Issue by lolpero** [SmashMC-Development/Bugs-and-Issues#1884]
i cannot send out my pokemon

i cant send out my pokemon on any server even singleplayer
I think it's because I made a ticket for a report of a bug I encountered where I couldn't use the RTP command and when this bug was fixed I couldn't send out my Pokemon

N/A

N/A

**Comment by Paradis4432** [comment]
you have your R bind set to something else, likely because of some mod you installed, press ESC -> controls -> at the bottom it says "send out pokemon" make sure its not red
![image](https://github.com/SmashMC-Development/Bugs-and-Issues/assets/49301263/2efa689c-01d3-4472-8dc0-fdfce8ec82b1)
if it is find what else is set to R and move it to some other key, until the send out pokemon is not red

**Comment by lolpero** [comment]
thanks for help
