### ISSUE TITLE
Attack of the pidoves

### ISSUE THREAD

**Issue by LittleBunnyFuuFuu** [SmashMC-Development/Bugs-and-Issues#198]
**Describe the Bug**
Warzone. Pidoves. SO MANY. Breeding faster than rabbits. I should know, I'm a rabbit.

**To Reproduce**
1. Go to warzone
2. Pidove

**Servers with the Bug**
Jirachi

**Expected behavior**
Less Pidoves 

**Screenshots**
N/A

**Additional context**
I'm not scared of birds.

**Comment by Mikirae** [comment]
Pidoves do have the same rate as the rest of the Warzone spawns. I believe that the only reason there are more is because they naturally spawn there as it's their biome. I'm sure some other Extreme Hills mons spawn there as well. (If that's the biome. I forget) 

This is something that can easily be addressed upon the rewrite of Warzone. :)
