### ISSUE TITLE
Lorkeeper Glitched

### ISSUE THREAD

**Issue by DragonBallBreakersRandomizer** [SmashMC-Development/Bugs-and-Issues#238]
**Describe the Bug**
Electric eagle quest is not displaying certain NPC name in bottom right

**To Reproduce**
1. Get the Electric Eagle Quest
2. do the quest until the final part until it wants you to return to the npc
3. the quest will be glitched
**Servers with the Bug**
Idk but mines on jirachi

**Expected behavior**
Should
 point me to the lore keeper

**Screenshots**
![2021-05-31 (4)](https://user-images.githubusercontent.com/84050975/120213691-7fcf9b00-c201-11eb-8fc4-8c3aa22e99dc.png)

**Additional context**
'N/A'.

**Comment by HackuJacku** [comment]
Spoke to Waterdude regarding this, the files are fine. This has been caused by the inserters (?NAME?) being changed as part of 8.2. If you had the quest before the update, this would occur. There are other ways this could occur but I'm unable to remember off the top of my head.

If you're unable to progress on the quest however, please create a ticket and we'll help you there!
