### ISSUE TITLE
revert warzone and tournament to previous update.

### ISSUE THREAD

**Issue by IAmSkidd7** [SmashMC-Development/Bugs-and-Issues#327]
Ever since the latest update to warzone that removes textured legends/ultrabeasts it has become very apparent that it has upset a lot of the player base. It says that it ruins the economy by them being so common. then wouldn't the logical next step to take be to lower the rarity of textures in warzone? Not jump to the extreme of removing them all together? I believe this was a rash decision made to make the server more money by having the only way to get textured legends be through microtransactions, and yes I know vote party exists but the likelihood of you getting a textured from that is already small. The servers always feel like 1 step forward and 2 steps backwards. most of the servers are dying as we speak. economy is non existent on most servers to begin with, and the reduction of tournament rewards doesn't help, why would players waste their time doing a tournament that barely works half of the time and the rewards are awful, rare candies aren't rare and money cant be used to purchase anything because their is no incentive to sell items on the gts. Staff always says they're listening but half the thing the community begs for falls on deaf ears. but please do something i would hate for the servers to completely die, but its heading in that direction, and as a long time player at this point it hurts to see you guys shoot yourselves in the foot over and over. and please for the love of god add back auto jailing in wz. its easier to prove you crashed in wz then try and record every time someone logs in wz. and please make a baseline for what evidence is, as for it is different for every staff member i feel like.

**Comment by bladegalaxy** [comment]
Please also provide some compensation for players in Deoxys too the rollback did a lot of harm and all we get is an apology saying you tried your best. At least give us 1 crate key or any form of compensation

**Comment by Rasgnarok** [comment]
That's a fair few different issues in your post, and most of them are more fitting of https://github.com/SmashMC-Development/Suggestions/issues . I recommend splitting your issue into several tickets. That said, here's a rounded answer for the points you bring up.

> the latest update to warzone that removes textured legends/ultrabeasts it has become very apparent that it has upset a lot of the player base. It says that it ruins the economy by them being so common. then wouldn't the logical next step to take be to lower the rarity of textures in warzone?

No, because not all fixes are lower -> remove. Textured pokémon were too common in Warzone, and were meant to be an exclusive from the beginning. Their rarity levels were skewed thanks to a poorly coded plugin (Warzone), and as such, we removed them completely, as they were no longer the exclusive reward they were meant to be.

> I believe this was a rash decision made to make the server more money by having the only way to get textured legends be through microtransactions

Being a cosmetic item, they are absolutely bound to be rarer and more exclusive, be it from the Store or Vote Parties. The idea is to incentivize, and in this case, the fact they were in Warzone made the other two methods of obtention meaningless, when it came to textured legends and ultra beasts.

> most of the servers are dying as we speak.

Most of the servers are due for resets and absolutely need some QoL work. Warzone is meant to be completely swapped out for a new plugin. Your statement is invalid however - because the spikes in playercounts we see are irrespective of the slow, but steady, climb of our network's popularity. 

> why would players waste their time doing a tournament that barely works half of the time and the rewards are awful, 

I recommend making a suggestion ticket about what rewards you'd like to see for tournaments.

> rare candies aren't rare and money cant be used to purchase anything because their is no incentive to sell items on the gts

If you are interested in helping us fix the economy, here's a _fair few_ tickets we would love input on. Too many people complain and never become part of the solution, https://github.com/SmashMC-Development/Suggestions/issues/522.

> Staff always says they're listening but half the thing the community begs for falls on deaf ears.

I am taking my time to reply to every point in your ticket. You might have that impression, but #announcements on our Discord clearly shows staff listens. Feel free to DM me on Discord if you want to report issues privately, however.

> and please for the love of god add back auto jailing in wz

Auto-jailing was not evenly distributing the jailing penalty, and was overall extremely unfair for players that were jailed by crash that aren't their fault. It would also not address the issues with disconnects in WZ, because most players happily took the jail time if it meant evading a battle. If you have a suggestion that actually addresses that issue, please let me know.

> please make a baseline for what evidence is

Logs are the baseline. It's written to #support on our Discord when you make a ticket.

**Comment by Rasgnarok** [comment]
Closing this ticket as it isn't a bug or issue, but please move the separate arguments to suggestions as I mention, some of these points are absolutely things we want to hear more about.
