### ISSUE TITLE
in clam block building glitches

### ISSUE THREAD

**Issue by ZAPZ9** [SmashMC-Development/Bugs-and-Issues#671]
**Describe the Bug**
building in clam area of mine and blocks getting replaced with other blocks in hotbar with the previous block disappearing 

**Servers with the Bug**
rayquazza

**Expected behavior**
so its been happening everyday today and ive relogged so many times to fix it but it keeps happening its also happening out side of the claim blocks aswell for me at least i dont know whats happening but its kinda getting annoying having to re log every time to fix it  

**Screenshots**
NA

(p.s sorry if its not right the report its my first time doing it but hope you can fix it)

**Comment by Mikirae** [comment]
Do you have some sort of inventory mod in your mods folder? That's the only thing I can think of since I've heard of no one else with this issue unfortunately. 
The only other times I've had something similar to this was when I was lagging really hard, but relogging fixed it for me. Never had it happen a lot in a row.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
