### ISSUE TITLE
Falling star

### ISSUE THREAD

**Issue by lensiemar** [SmashMC-Development/Bugs-and-Issues#799]
**Describe the Bug**
I completed the falling star objective (the both) but i didn't get the dynamax band
**To Reproduce**

**Servers with the Bug**
Please provide a list of which servers have this bug.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. If not, please add 'N/A'.

**Additional context**
Add any other context about the problem here. If nothing, please add 'N/A'.

**Comment by ehhhkody** [comment]
I completed the first part of the quest, and I'm in the same village and am unable to progress past the first stage. I play on Zekrom.

**Comment by Mikirae** [comment]
Do you know what the quest name is exactly? I'm looking in the quest files and not seeing anything named Falling Star.

**Comment by ehhhkody** [comment]
I think it's called "shooting star"

Sent from Yahoo Mail on Android 
 
  On Fri, Nov 19, 2021 at 10:49 PM, ***@***.***> wrote:   


Do you know what the quest name is exactly? I'm looking in the quest files and not seeing anything named Falling Star.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Archie4690** [comment]
Purging all old GitHub reports. Thank you for your contributions!
