### ISSUE TITLE
Pokémon moves problems

### ISSUE THREAD

**Issue by WorkableSutoresu** [SmashMC-Development/Bugs-and-Issues#895]
**Describe the Bug**
Some Pokémon aren't learning moves that they are supposed to be able to learn based on the Pokédex 
For example, Pelipper is supposed to be able to learn defog and yet it can't and another one is Swirlix is supposed to be able to learn belly drum and it can't learn it through a move tutor or even through breeding and another one is Marill is supposed to be able to learn knock off but it can't also.

**Servers with the Bug**
Probably all servers but mainly Groudon

**Additional context**
N/A

**Comment by ghost** [comment]
Something really needs to be done about the moves....because it gets very annoying that a mon can't learn the particular move after searching for a move tutor with that move for a whole week
![Screenshot (691)](https://user-images.githubusercontent.com/25759066/144554663-ae20a674-7dd4-4301-a6a7-3eefc63ebc65.png)
![Screenshot (692)](https://user-images.githubusercontent.com/25759066/144554666-cc28711f-6475-4f20-bc37-9594b00f6b13.png)
![Screenshot (693)](https://user-images.githubusercontent.com/25759066/144554667-04c40966-0d78-4b3e-8a8f-df2609d645d1.png)
.

**Comment by ghost** [comment]
![Screenshot (694)](https://user-images.githubusercontent.com/25759066/144568043-d0c99997-8a40-40cd-b587-ccfba070b963.png)

**Comment by HackuJacku** [comment]
It's an issue on the default Pixelmon stat files, it's a case by case fix. Majority of cases are fixed when we update to 8.3.4.

**Comment by ghost** [comment]
okay thank you
