### ISSUE TITLE
/redeem gui doesn't work on Kyurem

### ISSUE THREAD

**Issue by Lun17** [SmashMC-Development/Bugs-and-Issues#922]
**Describe the Bug**
The command /redeem gui doesn't work on Kyurem, the commands /redeemcosm or /redeemcosmetics works but you are not able to redeem any scarf

**To Reproduce**
1. Go to 'kyurem server"
2. Type /redeem guy

yes of course im a smash rank.

**Comment by Mikirae** [comment]
Does the GUI not open?
And did you purchase Smash Rank before or after reset?

**Comment by Lun17** [comment]
Yep it does not open.
When you type the command it goes through but nothing happens


Il giorno mar 7 dic 2021 alle ore 22:18 Mikirae ***@***.***>
ha scritto:

**Comment by Lun17** [comment]
> Does the GUI not open? And did you purchase Smash Rank before or after reset?

Didnt read the second part, sorry Miki, as your favorite italian person you should know that i bought it before the reset ;)

**Comment by Mikirae** [comment]
> > Does the GUI not open? And did you purchase Smash Rank before or after reset?
> 
> Didnt read the second part, sorry Miki, as your favorite italian person you should know that i bought it before the reset ;)

Hey bb <3 HOW HAVE YOU BEEN?  I didn't read the name when I replied. Lmao. You don't get the scarves if you bought before reset as they're basically just an item

**Comment by Lun17** [comment]
Oh i get it :P 
Ive been good thanks :D

**Comment by HackuJacku** [comment]
`/redeem gui` is part of Pixelmon. You need to link your Minecraft and PixelmonMod accounts, that's why it doesn't work for you. I have linked accounts, it works perfectly fine for me.

RedeemCos is a separate entity. It's used for Eevee Scarfs. 

This is an issue with you not having linked accounts - contact me directly and I'll show you how to link your accounts.
