### ISSUE TITLE
Smash MC Texture Pack

### ISSUE THREAD

**Issue by AstroLuvsMemes** [SmashMC-Development/Bugs-and-Issues#952]
When clicking on the link given in the smashmc discord server for the texture pack,
the tab opens but seconds later it automatically closes, it doesnt appear in the downloads folder too after clicking the link

**Comment by Sparklix** [comment]
**Describe the Bug**
When clicking the texturepack link on the discord, it opens a new tab on the user his browser but immediately closes it again.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to discord, smashmc info
2. Click on texturepack link
3. See error

**Servers with the Bug**
Discord

**Expected behavior**
Start downloading texturepack

**Screenshots**
https://user-images.githubusercontent.com/77632744/146327027-5b0f2209-2c50-43ac-947f-e0ce7949c532.mov

**Additional context**
N/A

https://user-images.githubusercontent.com/77632744/146327027-5b0f2209-2c50-43ac-947f-e0ce7949c532.mov

**Comment by HackuJacku** [comment]
Works fine and downloads. If it's still an issue, please create a new issue with full, specific details.
